title: Shervin's Kaday
lang: en
description: Loves making Sri Lankan cuisines and my way of sharing this love!

# For GitHub Pages project site (shervinfernando.github.io/shervins-kaday)
baseurl: "/shervins-kaday"
url: "https://shervinfernando.github.io"

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - .DS_Store
  - images/README.md
